# Generated by Django 4.2.2 on 2023-06-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_category_product_sub_categorycategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_Categorycategory',
            new_name='sub_category',
        ),
    ]
