# Generated by Django 4.2.2 on 2023-06-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='Profile_image',
        ),
    ]
